[workspace]
authors = ["Jonathan Leeming <jonathan@leeming.dev>"]
channels = ["conda-forge"]
name = "recipes.leeming.dev"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
dev = "yarn dev"

[dependencies]
nodejs = ">=24.4.1,<24.5"
